version: '3.4'

volumes:
  postgresql_data:
    name: postgresql_data

services:
   db:
     image: postgres
     restart: always
     environment:
       POSTGRES_PASSWORD: example
       PGDATA: /var/lib/postgresql/data/pgdata
     volumes:
       - postgresql_data:/var/lib/postgresql/data/pgdata
     ports:
       - "5432:5432"

   itstiloop:
     image: ${DOCKER_REGISTRY-}itstiloop
     build:
       context: .
       dockerfile: ITSTILoop/Dockerfile
     environment:
       DB_CONNECTION: PostgresComposeConnection
       SAMPLE_FSP_1: bankbethesda|BETHESDAAPIID|BETHESDAAPIKEY
       SAMPLE_FSP_1_PARTIES: Mert:Ozdag:5551234567|Ava:Jeay:5551234568
     depends_on:
       - db

   bankbethesda:
     image: ${DOCKER_REGISTRY-}itstiloopsamplefsp
     build:
       context: .
       dockerfile: ITSTILoopSampleFSP/Dockerfile
     environment:
       PARTICIPANT_ID: 1
       ITSTILOOP_URI: http://itstiloop/
       ITSTILOOP_API_ID: BETHESDAAPIID
       ITSTILOOP_API_KEY: BETHESDAAPIKEY
       ACCOUNTS: Mert:Ozdag:5551234567:10000|Ava:Jeay:5551234568:20000
     depends_on:
       - itstiloop     