version: '3.4'

volumes:
  postgresql_data:
    name: postgresql_data

services:   
   reverse-proxy:     
      image: mozdag.azurecr.io/reverseproxysec2
      ports:
        - "80:80"
        - "443:443"

   db:
     image: postgres
     restart: always
     environment:
       POSTGRES_PASSWORD: example
       PGDATA: /var/lib/postgresql/data/pgdata
     volumes:
       - postgresql_data:/var/lib/postgresql/data/pgdata
     ports:
       - "5432:5432"

   globalpartylookup:
     image: mozdag.azurecr.io/globalpartylookup
     build:
       context: .
       dockerfile: ITSTILoopAddressLookup/Dockerfile
     environment:
       GLOBAL_ADDRESS_LOOKUP_PARTIES: ${GLOBAL_PARTIES}

   itstiloop:
     image: mozdag.azurecr.io/itstiloop
     build:
       context: .
       dockerfile: ITSTILoop/Dockerfile
     environment:
       DB_CONNECTION: PostgresComposeConnection
       SAMPLE_FSP_2: CBDC|CBDCAPIID|CBDCAPIKEY|0x34
       SAMPLE_FSP_2_PARTIES: 5551234569|5551234566
     ports:
       - "8081:80"
     depends_on:
       - db

   bankbethesda:
     image: mozdag.azurecr.io/itstiloopsamplefsp
     build:
       context: .
       dockerfile: ITSTILoopSampleFSP/Dockerfile
     environment:
       FSP_NAME: BANKBETHESDA
       PARTICIPANT_ID: 1
       ITSTILOOP_URI: http://itstiloop/
       ITSTILOOP_API_ID: BETHESDAAPIID
       ITSTILOOP_API_KEY: BETHESDAAPIKEY
       ACCOUNTS: Mert:Ozdag:5551234567:250|Ava:Jeay:5551234568:250
       IS_LOOP_PARTICIPANT: false
       GLOBAL_ADDRESS_LOOKUP_URL: http://globalpartylookup/Party
       CBDC_TRANSFER_CONTRACT_ADDRESS: 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
       CBDC_RPC_ENDPOINT: https://cbdcuser:testTEST11@cbdcethereum.azurewebsites.net
       CBDC_NETWORK_ID: 31337
       CBDC_TRANSFER_CONTRACT_OWNER_KEY: ${BETHESDAKEY}
     ports:
       - "8083:80"
     depends_on:
       - itstiloop
       - globalpartylookup
   cbdc:
     image: mozdag.azurecr.io/itstiloopcbdcadapter
     build:
       context: .
       dockerfile: ITSTILoopCBDCAdapter/Dockerfile
     environment:
       ITSTILOOP_URI: http://itstiloop/
       ITSTILOOP_API_ID: CBDCAPIID
       ITSTILOOP_API_KEY: CBDCAPIKEY
       CBDC_TRANSFER_CONTRACT_ADDRESS: 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
       CBDC_RPC_ENDPOINT: https://cbdcuser:testTEST11@cbdcethereum.azurewebsites.net
       CBDC_NETWORK_ID: 31337
       CBDC_TRANSFER_CONTRACT_OWNER_KEY: ${CBDCKEY}
     ports:
       - "8084:80"
     depends_on:
       - itstiloop  

   bankprincegeorge:
     image: mozdag.azurecr.io/itstiloopsamplefsp
     build:
       context: .
       dockerfile: ITSTILoopSampleFSP/Dockerfile
     environment:
       FSP_NAME: BANKPRINCEGEORGE
       PARTICIPANT_ID: 3
       ITSTILOOP_URI: http://itstiloop/
       ITSTILOOP_API_ID: PRINCEGEORGEAPIID
       ITSTILOOP_API_KEY: PRINCEGEORGEAPIKEY
       ACCOUNTS: Grace:Crown:5551234559:250|Abigail:Crown:5551234556:250
     ports:
       - "8085:80"
     depends_on:
       - itstiloop