version: '3.4'

volumes:
  postgresql_data:
    name: postgresql_data

services:
   reverse-proxy:     
     image: mozdag.azurecr.io/reverseproxysec2
     build:
       context: ./ReverseProxy
       dockerfile: Dockerfile       
     ports:
       - "80:80"
       - "443:443"
     depends_on:
       - itstiloop

   db:
     image: postgres
     restart: always
     environment:
       POSTGRES_PASSWORD: example
       PGDATA: /var/lib/postgresql/data/pgdata
     volumes:
       - postgresql_data:/var/lib/postgresql/data/pgdata
     ports:
       - "5432:5432"

   globalpartylookup:
     image: mozdag.azurecr.io/globalpartylookup
     build:
       context: .
       dockerfile: ITSTILoopAddressLookup/Dockerfile
     environment:
       GLOBAL_ADDRESS_LOOKUP_PARTIES: 5552234567:cbdc:0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC|5551234567:itstiloop:bankbethesda|5551234568:itstiloop:bankbethesda|5551234559:itstiloop:bankprincegeorge|5551234556:itstiloop:bankprincegeorge
     ports:
       - "8086:80"

   itstiloop:
     image: mozdag.azurecr.io/itstiloop
     build:
       context: .
       dockerfile: ITSTILoop/Dockerfile
     environment:
       GLOBAL_ADDRESS_LOOKUP_URL: http://globalpartylookup/Party
       DB_CONNECTION: PostgresComposeConnection
       SAMPLE_FSP_1: bankbethesda|BETHESDAAPIID|BETHESDAAPIKEY|0xE1A6dc4e3Bdb3A8384181a9F70aB76642762557b
       SAMPLE_FSP_1_PARTIES: 5551234567|5551234568
       SAMPLE_FSP_2: cbdc|CBDCAPIID|CBDCAPIKEY|0x34A816710f52a75F4430674a12E2Ad9De1092e86
       SAMPLE_FSP_2_PARTIES: 5551234569|5551234566
       SAMPLE_FSP_3: bankprincegeorge|PRINCEGEORGEAPIID|PRINCEGEORGEAPIKEY|0x6a82bf493725771AD037DD0cf1ABa956e73C18ff
       SAMPLE_FSP_3_PARTIES: 5551234559|5551234556
       CBDCBridgeEventWatcherConfig__Address: 0x69282EFd96cd19d747944A9FB358feBaf8c16a2D
       CBDCBridgeEventWatcherConfig__RpcEndpoint: https://cbdcuser:testTEST11@cbdcethereum.azurewebsites.net
       CBDCBridgeEventWatcherConfig__NetworkId: 31337
       CBDCBridgeEventWatcherConfig__Key: 0xb5cc3ddbd4dacedd91eea5994c6cbbcd02b9b8644f89ef4576ce9bad2ae104be
     ports:
       - "8081:80"
     depends_on:
       - db

   bankbethesda:
     image: mozdag.azurecr.io/itstiloopsamplefsp
     build:
       context: .
       dockerfile: ITSTILoopSampleFSP/Dockerfile
     environment:
       FSP_NAME: BANKBETHESDA
       PARTICIPANT_ID: 1
       ITSTILOOP_URI: http://itstiloop/
       ITSTILOOP_API_ID: BETHESDAAPIID
       ITSTILOOP_API_KEY: BETHESDAAPIKEY
       ACCOUNTS: Mert:Ozdag:5551234567:250|Ava:Jeay:5551234568:250
       IS_LOOP_PARTICIPANT: false
       GLOBAL_ADDRESS_LOOKUP_URL: http://globalpartylookup/Party
       CBDCTransferConfig__Address: 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9
       CBDCTransferConfig__RpcEndpoint: https://cbdcuser:testTEST11@cbdcethereum.azurewebsites.net
       CBDCTransferConfig__NetworkId: 31337
       CBDCTransferConfig__Key: 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
     ports:
       - "8083:80"
     depends_on:
       - itstiloop
       - globalpartylookup
   cbdc:
     image: mozdag.azurecr.io/itstiloopcbdcadapter
     build:
       context: .
       dockerfile: ITSTILoopCBDCAdapter/Dockerfile
     environment:
       ITSTILOOP_URI: http://itstiloop/
       ITSTILOOP_API_ID: CBDCAPIID
       ITSTILOOP_API_KEY: CBDCAPIKEY
       CBDCTransferConfig__Address: 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9
       CBDCTransferConfig__RpcEndpoint: https://cbdcuser:testTEST11@cbdcethereum.azurewebsites.net
       CBDCTransferConfig__NetworkId: 31337
       CBDCTransferConfig__Key: 0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a
       CBDCTransferConfig__OwnerKey: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
     ports:
       - "8084:80"
     depends_on:
       - itstiloop  
       
   bankprincegeorge:
     image: mozdag.azurecr.io/itstiloopsamplefsp
     build:
       context: .
       dockerfile: ITSTILoopSampleFSP/Dockerfile
     environment:
       FSP_NAME: BANKPRINCEGEORGE
       PARTICIPANT_ID: 3
       ITSTILOOP_URI: http://itstiloop/
       ITSTILOOP_API_ID: PRINCEGEORGEAPIID
       ITSTILOOP_API_KEY: PRINCEGEORGEAPIKEY
       ACCOUNTS: Grace:Crown:5551234559:250|Abigail:Crown:5551234556:250
       CBDCTransferConfig__Address: 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9
       CBDCTransferConfig__RpcEndpoint: https://cbdcuser:testTEST11@cbdcethereum.azurewebsites.net
       CBDCTransferConfig__NetworkId: 31337
       CBDCTransferConfig__Key: 0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a
     ports:
       - "8085:80"
     depends_on:
       - itstiloop  