version: '3.4'

volumes:
  postgresql_data:
    name: postgresql_data

services:
   pg-admin:
     image: dpage/pgadmin4
     environment:
       PGADMIN_DEFAULT_EMAIL: user@domain.com
       PGADMIN_DEFAULT_PASSWORD: SuperSecret
     ports:
       - "80:80"
   
   reverse-proxy:     
     image: ${DOCKER_REGISTRY-}reverseproxy
     build:
       context: ./ReverseProxy
       dockerfile: Dockerfile       
     ports:
       - "80:80"
       - "443:443"

   db:
     image: postgres
     restart: always
     environment:
       POSTGRES_PASSWORD: example
       PGDATA: /var/lib/postgresql/data/pgdata
     volumes:
       - postgresql_data:/var/lib/postgresql/data/pgdata
     ports:
       - "5432:5432"

   itstiloop:
     image: ${DOCKER_REGISTRY-}itstiloop
     build:
       context: .
       dockerfile: ITSTILoop/Dockerfile
     environment:
       DB_CONNECTION: PostgresComposeConnection
       SAMPLE_FSP_1: bankbethesda|BETHESDAAPIID|BETHESDAAPIKEY|0xE1A6dc4e3Bdb3A8384181a9F70aB76642762557b
       SAMPLE_FSP_1_PARTIES: 5551234567|5551234568
       SAMPLE_FSP_2: bankwheaton|WHEATONAPIID|WHEATONAPIKEY|0x34A816710f52a75F4430674a12E2Ad9De1092e86
       SAMPLE_FSP_2_PARTIES: 5551234569|5551234566
       SAMPLE_FSP_3: bankprincegeorge|PRINCEGEORGEAPIID|PRINCEGEORGEAPIKEY|0x6a82bf493725771AD037DD0cf1ABa956e73C18ff
       SAMPLE_FSP_3_PARTIES: 5551234559|5551234556
     ports:
       - "8081:80"
     depends_on:
       - db

   bankbethesda:
     image: ${DOCKER_REGISTRY-}itstiloopsamplefsp
     build:
       context: .
       dockerfile: ITSTILoopSampleFSP/Dockerfile
     environment:
       FSP_NAME: BANKBETHESDA
       PARTICIPANT_ID: 1
       ITSTILOOP_URI: http://itstiloop/
       ITSTILOOP_API_ID: BETHESDAAPIID
       ITSTILOOP_API_KEY: BETHESDAAPIKEY
       ACCOUNTS: Mert:Ozdag:5551234567:250|Ava:Jeay:5551234568:250
     ports:
       - "8083:80"
     depends_on:
       - itstiloop

   bankwheaton:
     image: ${DOCKER_REGISTRY-}itstiloopsamplefsp
     build:
       context: .
       dockerfile: ITSTILoopSampleFSP/Dockerfile
     environment:
       FSP_NAME: BANKWHEATON
       PARTICIPANT_ID: 2
       ITSTILOOP_URI: http://itstiloop/
       ITSTILOOP_API_ID: WHEATONAPIID
       ITSTILOOP_API_KEY: WHEATONAPIKEY
       ACCOUNTS: Clemence:Jeay:5551234569:250|Ella:Jeay:5551234566:250
     ports:
       - "8084:80"
     depends_on:
       - itstiloop  
       
   bankprincegeorge:
     image: ${DOCKER_REGISTRY-}itstiloopsamplefsp
     build:
       context: .
       dockerfile: ITSTILoopSampleFSP/Dockerfile
     environment:
       FSP_NAME: BANKPRINCEGEORGE
       PARTICIPANT_ID: 3
       ITSTILOOP_URI: http://itstiloop/
       ITSTILOOP_API_ID: PRINCEGEORGEAPIID
       ITSTILOOP_API_KEY: PRINCEGEORGEAPIKEY
       ACCOUNTS: Grace:Crown:5551234559:250|Abigail:Crown:5551234556:250
     ports:
       - "8085:80"
     depends_on:
       - itstiloop  